const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const addCSS=c=>{const s=document.createElement('style');s.textContent=c;document.head.append(s)};
const header=$('[data-header]'),menu=$('.menu-toggle'),nav=$('.site-nav');
const headerState=()=>header?.classList.toggle('scrolled',scrollY>24);headerState();addEventListener('scroll',headerState,{passive:true});
menu?.addEventListener('click',()=>{const o=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!o));nav?.classList.toggle('open',!o);document.body.classList.toggle('menu-open',!o)});
$$('a',nav).forEach(a=>a.addEventListener('click',()=>{menu?.setAttribute('aria-expanded','false');nav?.classList.remove('open');document.body.classList.remove('menu-open')}));
const p=Object.fromEntries(new Intl.DateTimeFormat('en',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).map(x=>[x.type,x.value])),today=`${p.year}-${p.month}-${p.day}`,eventSec=$('[data-event-section]');
$$('[data-event-date]',eventSec).forEach(x=>{if(x.dataset.eventDate<today)x.remove()});if(eventSec&&!$('[data-event-date]',eventSec)){eventSec.remove();$('[data-event-nav]')?.remove()}
const dlg=$('[data-competition-dialog]'),openDlg=()=>{if(!dlg)return;dlg.showModal?dlg.showModal():dlg.setAttribute('open','');document.body.classList.add('dialog-open')},closeDlg=()=>{if(!dlg)return;dlg.close?dlg.close():dlg.removeAttribute('open');document.body.classList.remove('dialog-open')};
$('[data-competition-open]')?.addEventListener('click',openDlg);$('[data-competition-close]')?.addEventListener('click',closeDlg);dlg?.addEventListener('close',()=>document.body.classList.remove('dialog-open'));dlg?.addEventListener('click',e=>{if(e.target===dlg)closeDlg()});

const story=$('#about .story-feature');if(story&&!$('.brazil-story'))story.insertAdjacentHTML('afterend',`<article class="brazil-story"><div><p class="eyebrow"><span></span> Brazil 2014 · Football Dream</p><h3>和昔日隊友一起，走進真正的<span>世界盃。</span></h3><p>因為真的太喜歡足球，2014 年我和以前足球隊的朋友相約前往巴西，親眼看夢想中的世界盃。這不只是一趟旅行，也是人生中很重要的一個願望。</p><blockquote>足球把友情、夢想與世界各地的人連在一起。</blockquote></div><div class="brazil-gallery"><img src="assets/photos/brazil-2014/photo-1.svg" alt="里約基督像前合照"><img src="assets/photos/brazil-2014/photo-2.svg" alt="FIFA Fan Fest 合照"><img src="assets/photos/brazil-2014/photo-3.svg" alt="世界盃球場內合照"></div></article>`);

const services=$('#services'),serviceList=$('.service-list',services);if(serviceList&&!$('[data-lesson-plan]',services))serviceList.insertAdjacentHTML('afterend',`<article class="lesson-plan" data-lesson-plan><div><p class="eyebrow"><span></span> Freestyle Football Lesson Plan</p><h3>從第一下控球，練出自己的<span>節奏。</span></h3><p>兒童、青少年與成人皆可參加，零基礎也能從球感、控球、第一個花式動作一路完成小組合。</p><a class="button button-primary" href="https://www.facebook.com/share/r/1BWEJ2tgqP/?mibextid=wwXIfr" target="_blank" rel="noreferrer">觀看教學示範 ↗</a></div><ol><li><b>01 動態暖身與球感</b><span>熟悉足球重量與彈性</span></li><li><b>02 基礎控球</b><span>左右腳交換與穩定節奏</span></li><li><b>03 第一個花式動作</b><span>Foot Stall、ATW 或基礎 Transition</span></li><li><b>04 闖關與分組挑戰</b><span>把技術變成遊戲</span></li><li><b>05 成果分享</b><span>串成短組合並完成展示</span></li></ol></article>`);

const familyGrid=$('#natsuki .short-video-grid');if(familyGrid&&!$('[data-family-video-ils9]',familyGrid))familyGrid.insertAdjacentHTML('beforeend',`<article class="short-video-card featured" data-family-video-ils9><div class="short-video-frame"><iframe src="https://www.youtube-nocookie.com/embed/IlS9u0WfnFk" title="親子花式足球演出" loading="lazy" allowfullscreen></iframe></div><div class="short-video-copy"><p><span>04</span> FAMILY PERFORMANCE</p><h4>親子花式足球演出</h4><p>父女把技巧、節奏與默契帶上舞台。</p><a href="https://youtube.com/shorts/IlS9u0WfnFk" target="_blank" rel="noreferrer">前往 YouTube 觀看 ↗</a></div></article>`);

const works=$('#works');if(works&&!$('#signature-moves'))works.insertAdjacentHTML('beforebegin',`<section id="signature-moves" class="section signature-moves"><div class="section-number">技</div><div class="signature-shell"><div class="signature-heading"><p class="eyebrow"><span></span> Signature Moves · 球花寶典</p><h2>把擅長的招式，練成自己的<span>江湖名號。</span></h2><p>收藏我的代表技巧與舞台招式，之後會持續加入新的得意技。</p></div><article class="signature-card"><div class="signature-video"><iframe src="https://www.youtube-nocookie.com/embed/CFNJCOmJ7Kw" title="二刀流" loading="lazy" allowfullscreen></iframe></div><div class="signature-copy"><p>第一式 · TWO-BALL CONTROL</p><h3>二刀流</h3><strong>同時踢兩顆球</strong><span>雙球控制 · 節奏分離 · 左右腳協調</span><a href="https://youtube.com/shorts/CFNJCOmJ7Kw" target="_blank" rel="noreferrer">觀看完整招式 ↗</a></div></article><article class="signature-card"><div class="signature-video"><iframe src="https://www.youtube-nocookie.com/embed/WzilNdCLoDQ" title="繩球合一" loading="lazy" allowfullscreen></iframe></div><div class="signature-copy"><p>第二式 · FOOTBALL × JUMP ROPE</p><h3>繩球合一</h3><strong>足球結合跳繩</strong><span>節奏同步 · 空間判斷 · 跨界技巧</span><a href="https://youtube.com/shorts/WzilNdCLoDQ" target="_blank" rel="noreferrer">觀看完整招式 ↗</a></div></article></div></section>`);
const honors=$('#honors .honor-list');if(honors&&!$('[data-summer-circus-2026]',honors))honors.insertAdjacentHTML('afterbegin',`<article data-summer-circus-2026><time>2026</time><h3>臺中夏日馬戲節<br>Juggling Battle 邀請賽</h3><p>團體賽冠軍</p><a class="honor-video" href="https://www.facebook.com/share/r/19EXXkP5hy/?mibextid=wwXIfr" target="_blank" rel="noreferrer">觀看奪冠紀錄 ↗</a></article>`);

const about=$('#about');if(about&&!$('.home-quicknav'))about.insertAdjacentHTML('beforebegin',`<section class="home-quicknav"><p class="eyebrow"><span></span> Quick Route</p><h2>快速找到你想看的內容</h2><div><a href="#about">關於我<small>個人故事</small></a><a href="#natsuki">親子演出<small>父女同台</small></a><a href="#signature-moves">得意技<small>球花寶典</small></a><a href="#services">演出合作<small>商演與教學</small></a><a href="#honors">重要經歷<small>比賽紀錄</small></a><a href="#contact">聯絡邀約<small>快速洽詢</small></a></div></section>`);
const fold=(el,title,desc)=>{if(!el||el.parentElement?.classList.contains('fold-body'))return;const d=document.createElement('details');d.className='section-fold';d.innerHTML=`<summary><strong>${title}</strong><span>${desc}</span></summary><div class="fold-body"></div>`;el.before(d);$('.fold-body',d).append(el)};
fold($('.brazil-story'),'2014 巴西世界盃故事與照片','點擊展開旅程故事');fold($('#natsuki .family-videos'),'親子演出影片精選','點擊選擇影片');fold($('#services [data-lesson-plan]'),'花式足球教案','點擊查看完整課程流程');
const tabs=(cards,anchor,get)=>{if(cards.length<2||!anchor)return;const bar=document.createElement('div');bar.className='compact-tabs';cards.forEach((c,i)=>{const b=document.createElement('button');b.textContent=get(c,i);b.onclick=()=>{cards.forEach((x,j)=>x.hidden=j!==i);$$('button',bar).forEach((x,j)=>x.classList.toggle('on',j===i))};bar.append(b);if(i)c.hidden=true});anchor.after(bar);$('button',bar)?.classList.add('on')};
tabs($$('#natsuki .short-video-card'),$('#natsuki .family-video-heading'),(c,i)=>$('h4',c)?.textContent||`影片 ${i+1}`);tabs($$('#signature-moves .signature-card'),$('#signature-moves .signature-heading'),(c,i)=>$('h3',c)?.textContent||`招式 ${i+1}`);
if(honors){const items=$$('article',honors);if(items.length>4){const d=document.createElement('details');d.className='honor-more';d.innerHTML=`<summary>查看更多重要經歷（${items.length-4}）</summary><div></div>`;items.slice(4).forEach(x=>$('div',d).append(x));honors.after(d)}}

addCSS(`
.home-quicknav{max-width:var(--max);margin:0 auto;padding:0 0 52px}.home-quicknav h2{margin:8px 0 20px;font-size:clamp(30px,4vw,46px)}.home-quicknav>div{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.home-quicknav a{padding:16px;color:#fff;background:#111517;border:1px solid #ffffff14;font-weight:800}.home-quicknav small{display:block;margin-top:5px;color:#ffffff80;font-weight:500}
.section-fold{max-width:var(--max);margin:24px auto 0;background:#111517;color:#fff;border:1px solid #ffffff18}.section-fold summary{display:flex;justify-content:space-between;gap:20px;padding:18px 20px;cursor:pointer;list-style:none}.section-fold summary::-webkit-details-marker{display:none}.section-fold summary span{color:#ffffff85;font-size:11px}.fold-body{padding:0 18px 18px}.fold-body>*{margin-top:0!important}
.compact-tabs{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.compact-tabs button{padding:10px 13px;border:1px solid #ffffff1f;background:#13171a;color:#ffffffb0;font-weight:800}.compact-tabs button.on{background:var(--acid);color:#111;border-color:var(--acid)}
#natsuki .short-video-grid{display:block}.short-video-card[hidden],.signature-card[hidden]{display:none!important}
.signature-moves{color:#fff;background:#0a0d0e}.signature-shell{max-width:var(--max);margin:auto}.signature-heading{margin-bottom:34px}.signature-heading h2{font-size:clamp(44px,7vw,90px);line-height:1}.signature-heading h2 span{color:var(--acid)}.signature-card{display:grid;grid-template-columns:1.05fr .95fr;background:#15191b}.signature-video iframe{width:100%;min-height:560px;border:0}.signature-copy{display:flex;flex-direction:column;justify-content:center;gap:18px;padding:42px}.signature-copy h3{margin:0;font-size:clamp(62px,9vw,120px);line-height:.85}.signature-copy p{color:var(--acid);font-weight:800}.signature-copy strong{font-size:28px}.signature-copy span{color:#ffffff8c}.signature-copy a{color:var(--acid);font-weight:800}
.brazil-story{display:grid;grid-template-columns:.8fr 1.2fr;gap:38px;padding:38px;background:#090b0c}.brazil-story h3{font-size:clamp(34px,5vw,62px)}.brazil-story h3 span{color:var(--acid)}.brazil-story p,.brazil-story blockquote{color:#ffffffb0}.brazil-gallery{display:grid;grid-template-columns:2fr 1fr;gap:10px}.brazil-gallery img{width:100%;height:100%;object-fit:cover}.brazil-gallery img:first-child{grid-row:span 2}
.lesson-plan{display:grid;grid-template-columns:1fr 1fr;gap:38px;padding:38px;background:#0c1011}.lesson-plan h3{font-size:clamp(36px,5vw,66px)}.lesson-plan h3 span{color:var(--acid)}.lesson-plan ol{margin:0;padding:0;list-style:none}.lesson-plan li{display:flex;justify-content:space-between;gap:20px;padding:14px 0;border-bottom:1px solid #ffffff1c}.lesson-plan li span{color:#ffffff80}
.honor-more{max-width:var(--max);margin:20px auto 0;padding:16px 18px;background:#111517;color:#fff}.honor-more summary{cursor:pointer;font-weight:800}.honor-more>div{display:grid;grid-template-columns:repeat(2,1fr);gap:18px;margin-top:16px}
@media(max-width:900px){.home-quicknav>div{grid-template-columns:repeat(2,1fr)}.signature-card,.brazil-story,.lesson-plan{grid-template-columns:1fr}.signature-video iframe{min-height:500px}.honor-more>div{grid-template-columns:1fr}}
@media(max-width:620px){.section{padding-top:64px;padding-bottom:64px}.home-quicknav{padding:0 22px 34px}.home-quicknav>div{grid-template-columns:1fr}.home-quicknav a{padding:14px}.section-fold{margin-top:16px}.section-fold summary{display:block;padding:15px}.section-fold summary span{display:block;margin-top:6px}.fold-body{padding:0 12px 12px}.compact-tabs{overflow:auto;flex-wrap:nowrap;padding-bottom:4px}.compact-tabs button{flex:0 0 auto;white-space:nowrap}.short-video-frame iframe{width:100%;aspect-ratio:9/16;height:auto}.signature-card{margin-left:-22px;margin-right:-22px}.signature-video iframe{min-height:420px}.signature-copy{padding:32px 22px}.signature-copy h3{font-size:72px}.brazil-story,.lesson-plan{padding:24px 16px}.brazil-gallery{grid-template-columns:1fr 1fr}.brazil-gallery img:first-child{grid-column:1/3;grid-row:auto}.honor-more{margin:16px 22px 0}}
`);

const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches,items=$$('[data-reveal]');if(reduce||!('IntersectionObserver'in window))items.forEach(x=>x.classList.add('is-visible'));else{const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');o.unobserve(e.target)}}),{threshold:.13,rootMargin:'0px 0px -50px'});items.forEach(x=>o.observe(x))}
$('[data-year]').textContent=new Date().getFullYear();
